import { GetHomesParams } from "./server/types";

export const HOMES_PER_PAGE = 10;
export const paramImportance: (keyof GetHomesParams)[] = [
  "keyword_search",
  "min_bathroom",
  "min_price",
  "max_price",
  "pool_type",
  "has_fireplace",
  "max_year_built",
  "garage_spots",
  "has_waterfront",
  "has_include_outdoor_parking",
  "has_view",
  "max_bedroom",
  "min_bedroom",
  "max_square_feet",
  "min_square_feet",
  "max_stories",
  "min_stories",
  "min_year_built",
  "listing_type",
  "has_guest_house",
  "has_elevator",
  "has_basement",
  "has_washer_dryer_hookup",
  "has_pets_allowed",
  "has_primary_bedroom_on_main_floor",
  "has_rv_parking",
  "has_air_conditioning",
  "has_accessible_home",
  "has_green_home",
  "time_on_redfin",
];
